# Generated by Django 5.2.8 on 2025-11-06 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confessions", "0004_alter_comment_options_comment_is_edited_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="confession",
            field=models.ForeignKey(
                blank=True,
                help_text="Related confession (for admin notifications)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="confessions.confession",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("subscribe", "Subscribe"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("comment_like", "Comment Like"),
                    ("comment_reply", "Comment Reply"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="User who receives this notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
