# Generated by Django 5.2.8 on 2025-11-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confessions", "0005_alter_notification_confession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP for anonymous users", null=True
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to="confessions.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post View",
                "verbose_name_plural": "Post Views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "user", "-viewed_at"],
                        name="confessions_post_id_3f70c9_idx",
                    ),
                    models.Index(
                        fields=["post", "ip_address", "-viewed_at"],
                        name="confessions_post_id_8a1683_idx",
                    ),
                ],
            },
        ),
    ]
